### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by sapthasv** [ro6ley/python-ocr-example#4]
from the terminal its showing  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) but once we open in the browser, if we try to upload the image , its showing error , method not allowed, but if we append the upload like this "127.0.0.1:5000/upload " I am getting exact output, could you help out with this issue, what are all the changes required in the code

**Comment by ro6ley** [comment]
You want to use `127.0.0.1:5000` to upload the files?

**Comment by sapthasv** [comment]
if we go through 127.0.0.1:5000 it will redirect to index.html.
Now its working fine bro I commented(index.html path) that line in flask.
Thanks bro
