### ISSUE TITLE
tried to run available code of OCR but keep getting server error 

### ISSUE THREAD

**Issue by kazii21** [ro6ley/python-ocr-example#6]
#### Description

after uploading the image its doesnot give processed output, it only says server error

#### Steps to Reproduce

[https://github.com/ro6ley/python-ocr-example](url)  everytime i have to reinstall pillow to run the code 
`import os

from flask import Flask, render_template, request

from ocr_core import ocr_core

UPLOAD_FOLDER = '/static/uploads/'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])

app = Flask(__name__)

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/')
def home_page():
    return render_template('index.html')

@app.route('/upload', methods=['GET', 'POST'])
def upload_page():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            return render_template('upload.html', msg='No file selected')
        file = request.files['file']
        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            return render_template('upload.html', msg='No file selected')

        if file and allowed_file(file.filename):
            file.save(os.path.join(os.getcwd() + UPLOAD_FOLDER, file.filename))

            # call the OCR function on it
            extracted_text = ocr_core(file)

            # extract the text and display it
            return render_template('upload.html',
                                   msg='Successfully processed',
                                   extracted_text=extracted_text,
                                   img_src=UPLOAD_FOLDER + file.filename)
    elif request.method == 'GET':
        return render_template('upload.html')

if __name__ == '__main__':
    app.run()
`
`try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract

def ocr_core(filename):
    """
    This function will handle the core OCR processing of images.
    """
    text = pytesseract.image_to_string(Image.open(filename))  # We'll use Pillow's Image class to open the image and pytesseract to detect the string in the image
    return text  # Then we will print the text in the image
`
##### Expected Behavior

after running the code it gives a ip address where it  should say to upload a image after i upload the image it should display the letter present in the image

##### Actual Behavior

instead of displaying letters present in image its open a page saying internal server error 

#### Additional Information

also while running the code it says the error of no mudule named PIL and Image
![Screenshot (103)](https://user-images.githubusercontent.com/71893678/94332481-6d0f2180-fff5-11ea-87d3-e070d3fe6125.png)
![Screenshot (104)](https://user-images.githubusercontent.com/71893678/94332484-6ed8e500-fff5-11ea-8cc6-d85e9990b09b.png)
![Screenshot (105)](https://user-images.githubusercontent.com/71893678/94332517-b65f7100-fff5-11ea-943e-1329409ab6e9.png)
![Screenshot (106)](https://user-images.githubusercontent.com/71893678/94332519-b8293480-fff5-11ea-88fc-081fb9874d16.png)
![Screenshot (107)](https://user-images.githubusercontent.com/71893678/94332520-b8c1cb00-fff5-11ea-97b5-a3ad47e14571.png)
![Screenshot (108)](https://user-images.githubusercontent.com/71893678/94332521-b95a6180-fff5-11ea-9b7c-ce799b96e068.png)

**Comment by atnartur** [comment]
You need to install Tesseract with following instruction - https://github.com/tesseract-ocr/tesseract/wiki#windows. This link there is in Prerequisites section of this project's readme.

**Comment by ro6ley** [comment]
Thank you @atnartur . @kazii21 please try the solution suggested above
